ruleset:

  welcome:
    name: "Guide contributors to the contribution checklist and related material"
    events: [ issues, pull_request ]
    condition: action = "opened"
    comment: >
      Thanks for the {{ subject }}! Make sure it satisfies [this checklist](https://github.com/process-bot/contribution-checklist/blob/master/{{ subject = issue ? "issues" : "pulls" }}.md). My human colleagues will appreciate it!

      Here is [what to expect next](https://github.com/process-bot/contribution-checklist/blob/master/expectations.md), and if anyone wants to comment, keep [these things](https://github.com/process-bot/contribution-checklist/blob/master/participation.md) in mind.

  close_down:
    name: "Suggest to close down issues needing lengthy discussions"
    events: [ issue_comment ]
    conditions:
      - action = "created"
      - count(igrep("/(VarCI-bot)/", issue.commenters)) = 6
    comment: >
      This discussion has been going on for a while now. Let's:

      1. Close it down and summarize the state of affairs in a new issue

      2. Move the discussion somewhere else until it can be made more clear, or

      3. Keep talking in this thread after it's closed until we decide to do 1 or 2.

  contributors_agreement:
    name: "Check list of people who have given contributors agreements"
    events: [ pull_request ]
    conditions:
      - action = "created"
      - not (user.login in read("contributors.json", repository.full_name))
    comment: >
      Please sign the contributors agreement before this can be merged.
